"use client"
import { useState, type CSSProperties } from "react"
import { Checkbox } from "@/components/ui/checkbox"
type Node={id:string;label:string;children?:Node[]}
const tree:Node[]=[{id:"a",label:"لورم ایپسوم",children:[{id:"a1",label:"لورم ایپسوم",children:[{id:"a1a",label:"لورم ایپسوم متن ساختگی"},{id:"a1b",label:"لورم ایپسوم متن ساختگی"},{id:"a1c",label:"لورم ایپسوم متن ساختگی"}]},{id:"a2",label:"لورم ایپسوم",children:[{id:"a2a",label:"لورم ایپسوم متن ساختگی"},{id:"a2b",label:"لورم ایپسوم متن ساختگی"},{id:"a2c",label:"لورم ایپسوم متن ساختگی"}]},{id:"a3",label:"لورم ایپسوم",children:[{id:"a3a",label:"لورم ایپسوم متن ساختگی"},{id:"a3b",label:"لورم ایپسوم متن ساختگی"},{id:"a3c",label:"لورم ایپسوم متن ساختگی"}]}]},{id:"b",label:"لورم ایپسوم",children:[{id:"b1",label:"لورم ایپسوم",children:[{id:"b1a",label:"لورم ایپسوم متن ساختگی"},{id:"b1b",label:"لورم ایپسوم متن ساختگی"},{id:"b1c",label:"لورم ایپسوم متن ساختگی"}]},{id:"b2",label:"لورم ایپسوم",children:[{id:"b2a",label:"لورم ایپسوم متن ساختگی"},{id:"b2b",label:"لورم ایپسوم متن ساختگی"},{id:"b2c",label:"لورم ایپسوم متن ساختگی"}]},{id:"b3",label:"لورم ایپسوم",children:[{id:"b3a",label:"لورم ایپسوم متن ساختگی"},{id:"b3b",label:"لورم ایپسوم متن ساختگی"},{id:"b3c",label:"لورم ایپسوم متن ساختگی"}]}]},{id:"c",label:"لورم ایپسوم",children:[{id:"c1",label:"لورم ایپسوم",children:[{id:"c1a",label:"لورم ایپسوم متن ساختگی"},{id:"c1b",label:"لورم ایپسوم متن ساختگی"},{id:"c1c",label:"لورم ایپسوم متن ساختگی"}]},{id:"c2",label:"لورم ایپسوم",children:[{id:"c2a",label:"لورم ایپسوم متن ساختگی"},{id:"c2b",label:"لورم ایپسوم متن ساختگی"},{id:"c2c",label:"لورم ایپسوم متن ساختگی"}]},{id:"c3",label:"لورم ایپسوم",children:[{id:"c3a",label:"لورم ایپسوم متن ساختگی"},{id:"c3b",label:"لورم ایپسوم متن ساختگی"},{id:"c3c",label:"لورم ایپسوم متن ساختگی"}]}]},{id:"d",label:"لورم ایپسوم",children:[{id:"d1",label:"لورم ایپسوم",children:[{id:"d1a",label:"لورم ایپسوم متن ساختگی"},{id:"d1b",label:"لورم ایپسوم متن ساختگی"},{id:"d1c",label:"لورم ایپسوم متن ساختگی"}]},{id:"d2",label:"لورم ایپسوم",children:[{id:"d2a",label:"لورم ایپسوم متن ساختگی"},{id:"d2b",label:"لورم ایپسوم متن ساختگی"},{id:"d2c",label:"لورم ایپسوم متن ساختگی"}]},{id:"d3",label:"لورم ایپسوم",children:[{id:"d3a",label:"لورم ایپسوم متن ساختگی"},{id:"d3b",label:"لورم ایپسوم متن ساختگی"},{id:"d3c",label:"لورم ایپسوم متن ساختگی"}]}]}]
const treeArrow="/icons/tree-arrow.svg"
type SelectionState="checked"|"indeterminate"|"unchecked"
function leafIds(node:Node):string[]{return node.children?.length?node.children.flatMap(leafIds):[node.id]}
function selectionState(node:Node,selected:Set<string>):SelectionState{const leaves=leafIds(node);const count=leaves.filter(id=>selected.has(id)).length;return count===0?"unchecked":count===leaves.length?"checked":"indeterminate"}
function Branch({node,open,setOpen,selected,toggleSelection,level=0}:{node:Node;open:Set<string>;setOpen:(id:string)=>void;selected:Set<string>;toggleSelection:(node:Node)=>void;level?:number}){const expanded=open.has(node.id);const parent=Boolean(node.children?.length);const containsOpenChild=Boolean(node.children?.some(child=>open.has(child.id)));const inset=6+level*24+(level>1?6:0);const state=selectionState(node,selected);return <div className={`norato-tree-branch ${expanded?"is-expanded":""} ${level>0?"is-nested":""}`} role="treeitem" aria-level={level+1} aria-expanded={parent?expanded:undefined}><div className={`norato-tree-row ${expanded?"is-expanded":""}`} style={{"--norato-tree-inset":`${inset}px`} as CSSProperties}><Checkbox checked={state==="checked"} indeterminate={state==="indeterminate"} onChange={()=>toggleSelection(node)} aria-label={`انتخاب ${node.label}`} /><span className="norato-tree-label">{node.label}</span>{parent&&<button type="button" className="norato-tree-expand" onClick={()=>setOpen(node.id)} aria-expanded={expanded} aria-label={expanded?"بستن":"باز کردن"}><img className={`norato-tree-arrow ${expanded?"expanded":""} ${level>0?"nested":""}`} src={treeArrow} alt="" aria-hidden="true" /></button>}</div>{expanded&&<div className={`norato-tree-children ${containsOpenChild?"contains-open-child":""}`} role="group">{node.children?.map(child=><Branch key={child.id} node={child} open={open} setOpen={setOpen} selected={selected} toggleSelection={toggleSelection} level={level+1}/>)}</div>}</div>}
export function TreeView(){const [query,setQuery]=useState("");const [open,setOpenState]=useState<Set<string>>(new Set());const [selected,setSelectedState]=useState<Set<string>>(new Set(["a1a","a1c"]));const visible=tree.filter(node=>node.label.includes(query));const setOpen=(id:string)=>setOpenState(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n});const toggleSelection=(node:Node)=>setSelectedState(previous=>{const next=new Set(previous);const leaves=leafIds(node);const allSelected=leaves.every(id=>next.has(id));leaves.forEach(id=>allSelected?next.delete(id):next.add(id));return next});return <section className="tree-view-demo-card" aria-labelledby="tree-view-title"><h3 id="tree-view-title">Tree view</h3><div className="tree-view-card"><div className="tree-view-box"><label className="tree-view-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="لورم ایپسوم متن ساختگی با تولید" aria-label="جست‌وجو در ساختار" /><img src="/icons/tree-search.svg" alt="" aria-hidden="true" /></label><div className="tree-view-list" role="tree" aria-label="ساختار درختی">{visible.map(n=><Branch key={n.id} node={n} open={open} setOpen={setOpen} selected={selected} toggleSelection={toggleSelection}/>)}</div></div></div></section>}
